parallel-jobs = 4
dpi = "nodpi anydpi"
remove-rv-integrations-checks = false
# see https://github.com/nvbangg/Patches-APK-Builder/blob/main/CONFIG.md for more detailed explanations

# ==============================================================================
# MorpheApp/morphe-patches
# ==============================================================================

[YouTube-Morphe]
patches-source 	= "MorpheApp/morphe-patches"
cli-source 		= "MorpheApp/morphe-cli"
rv-brand 			= "morphe"
apkeep-dlurl 		= "com.google.android.youtube"

[YouTube-Morphe-Dev]
patches-source 		= "MorpheApp/morphe-patches"
cli-source 			= "MorpheApp/morphe-cli"
rv-brand 			= "morphe-dev"
patches-version 	= "dev"
apkeep-dlurl 		= "com.google.android.youtube"

[YouTube-Music-Morphe]
patches-source 	= "MorpheApp/morphe-patches"
cli-source 		= "MorpheApp/morphe-cli"
rv-brand		= "morphe"
uptodown-dlurl  = "https://youtube-music.en.uptodown.com/android"
apkeep-dlurl 	= "com.google.android.apps.youtube.music"

[YouTube-Music-Morphe-Dev]
patches-source 		= "MorpheApp/morphe-patches"
cli-source 			= "MorpheApp/morphe-cli"
rv-brand 			= "morphe-dev"
patches-version 	= "dev"
uptodown-dlurl  = "https://youtube-music.en.uptodown.com/android"
apkeep-dlurl 		= "com.google.android.apps.youtube.music"

[Reddit-Morphe]
patches-source 	= "MorpheApp/morphe-patches"
cli-source 		= "MorpheApp/morphe-cli"
rv-brand		= "morphe"
uptodown-dlurl  = "https://reddit-official-app.en.uptodown.com/android"
apkeep-dlurl  	= "com.reddit.frontpage"

[Reddit-Morphe-Dev]
patches-source 	= "MorpheApp/morphe-patches"
cli-source 		= "MorpheApp/morphe-cli"
rv-brand		= "morphe-dev"
patches-version = "dev"
uptodown-dlurl  = "https://reddit-official-app.en.uptodown.com/android"
apkeep-dlurl  	= "com.reddit.frontpage"

# ==============================================================================
# GitLab:Paresh-Maheshwari/paresh-patches
# ==============================================================================

[CREX]
patches-source  = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "paresh"
apkeep-dlurl 	= "in.cricketexchange.app.cricketexchange"

[Document-Scanner]
patches-source  = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "paresh"
# patches-version = "dev"
apkeep-dlurl = "com.cv.docscanner"

[Eyecon]
patches-source  = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "paresh"
apkeep-dlurl 	= "com.eyecon.global"

[Fing]
patches-source  = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "paresh"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/fing-limited/fing-network-tools/"
apkeep-dlurl  	= "com.overlook.android.fing"

[Lumina]
patches-source  = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "paresh"
apkeep-dlurl  = "com.lumina.wallpapers"

[MacroDroid]
patches-source  = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "paresh"
apkeep-dlurl 	= "com.arlosoft.macrodroid"

[MX-Player-Pro]
patches-source  = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/mx-media-entertainment-pte-ltd/mx-player-pro/"

[Telegram-Paresh]
patches-source  = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "paresh"
uptodown-dlurl = "https://telegram.en.uptodown.com/android"

[Truecaller]
patches-source  = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "paresh"
patches-version = "dev"
apkeep-dlurl 	= "com.truecaller"

# ==============================================================================
# hoo-dles/morphe-patches
# ==============================================================================

[AdGuard-hoo-dles]
patches-source  = "hoo-dles/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "hoo-dles"
apkeep-dlurl 	= "com.adguard.android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard/"

[CamScanner-hoo-dles]
patches-source  = "hoo-dles/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "hoo-dles"
apkeep-dlurl 	= "com.intsig.camscanner"

[ProtonVPN-Hoodles]
patches-source  = "hoo-dles/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "hoo-dles"
uptodown-dlurl  = "https://protonvpn.en.uptodown.com/android"

[Google-News-hoo-dles]
patches-source  = "hoo-dles/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "hoo-dles"
uptodown-dlurl 	= "https://google-play-newsstand.en.uptodown.com/android"

[Solid-Explorer]
patches-source  = "hoo-dles/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "hoo-dles"
apkeep-dlurl 	= "pl.solidexplorer2"

[Wallcraft]
patches-source  = "hoo-dles/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "hoo-dles"
apkeep-dlurl 	= "com.wallpaperscraft.wallpaper"

[WPS-Office]
patches-source  = "hoo-dles/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "hoo-dles"
apkeep-dlurl 	= "cn.wps.moffice_eng"

# ==============================================================================
# rushiranpise/morphe-patches
# ==============================================================================

[Amoledpix]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl   	= "com.androholic.amoledpix"

[AdGuard-rushiranpise]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl 	= "com.adguard.android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/adguard-software-limited/adguard/"

[Accuweather]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
# patches-version = "dev"
apkeep-dlurl 	= "com.accuweather.android"

[Apkmirror-Installer]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl 	= "com.apkmirror.helper.prod"

[CamScanner-rushiranpise]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl 	= "com.intsig.camscanner"

[Cloudflare-Warp]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkmirror-dlurl = "https://www.apkmirror.com/apk/cloudflare/1-1-1-1-faster-safer-internet/"

[Dailyhunt]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl	= "com.eterno"

[Greenify]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
# patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/oasis-feng/greenify/"

[Killapps]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl 	= "com.tafayor.killall"

[M-Indicator]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
# patches-version = "dev"
apkeep-dlurl  	= "com.mobond.mindicator"

[NZB360]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
# patches-version = "dev"
apkeep-dlurl 	= "com.kevinforeman.nzb360"

[Mega]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl	= "mega.privacy.android.app"

[MovieBox]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
uptodown-dlurl = "https://com-community-oneroom.en.uptodown.com/android"

[NYT-Crossword]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl	= "com.nytimes.crossword"

[ProtonVPN-Rushiranpise]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-free-vpn-secure-unlimited-fdroid-version/"
uptodown-dlurl  = "https://protonvpn.en.uptodown.com/android"

[Pocket-Prep]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl 	= "com.pocketprep.android.itcybersecurity"

[Playit]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl	= "com.playit.videoplayer"

[Psiphon]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
# patches-version = "dev"
uptodown-dlurl  = "https://psiphon-pro.en.uptodown.com/android"

[RS-File-Manager]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl	= "com.rs.explorer.filemanager"

[TeraBox]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl	= "com.dubox.drive"

[Unimote]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl	= "sensustech.universal.tv.remote.control"

[Yatri]
patches-source  = "rushiranpise/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "rushiranpise"
apkeep-dlurl 	  = "com.yatrirailways.yatri"

# ==============================================================================
# RookieEnough repositories (De-Vanced / De-ReVanced)
# ==============================================================================

[Adobe-Photoshop-Mix]
patches-source  = "RookieEnough/De-ReVanced"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "RookieEnough"
apkeep-dlurl  	= "com.adobe.photoshopmix"

[Cricbuzz]
patches-source  = "RookieEnough/De-ReVanced"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "RookieEnough"
uptodown-dlurl  = "https://cricbuzz-cricket-scores-and-news.en.uptodown.com/android"

[Google-Photos]
patches-source  = "RookieEnough/De-ReVanced"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "RookieEnough"
# patches-version = "dev"
apkeep-dlurl  	= "com.google.android.apps.photos"

[Google-News-RookieEnough]
patches-source  = "RookieEnough/De-ReVanced"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "RookieEnough"
uptodown-dlurl 	= "https://google-play-newsstand.en.uptodown.com/android"

[Icon-Pack-Studio]
patches-source  = "RookieEnough/De-ReVanced"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "RookieEnough"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[Irplus]
patches-source  = "RookieEnough/De-Vanced"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "RookieEnough"
apkeep-dlurl	= "net.binarymode.android.irplus"

[Letterboxd]
patches-source  = "RookieEnough/De-Vanced"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "RookieEnough"
apkeep-dlurl  	= "com.letterboxd.letterboxd"

[Photomath]
patches-source  = "RookieEnough/De-ReVanced"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "RookieEnough"
apkeep-dlurl	= "com.microblink.photomath"

[SoundCloud-RookieEnough]
patches-source  = "RookieEnough/De-Vanced"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "RookieEnough"
apkeep-dlurl  	= "com.soundcloud.android"

# ==============================================================================
# MiguelNinja19/miguel-morphe-patches
# ==============================================================================

[Anger-of-Stick-5]
patches-source  	= "MiguelNinja19/miguel-morphe-patches"
cli-source      	= "MorpheApp/morphe-cli"
rv-brand        	= "MiguelNinja19"
version 			= "latest"
apkeep-dlurl 		= "jpark.AOS5"

[Climb]
patches-source  	= "MiguelNinja19/miguel-morphe-patches"
cli-source      	= "MorpheApp/morphe-cli"
rv-brand        	= "MiguelNinja19"
version 			= "latest"
uptodown-dlurl 	= "https://climb-free.en.uptodown.com/android"

[CubeX-Solver]
patches-source  	= "MiguelNinja19/miguel-morphe-patches"
cli-source      	= "MorpheApp/morphe-cli"
rv-brand        	= "MiguelNinja19"
version 			= "latest"
apkeep-dlurl		= "diozz.cubex"

[Hunter-Assassin]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
apkeep-dlurl 	= "com.rubygames.assassin"

[Oddmar]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
apkeep-dlurl 	= "com.mobge.Oddmar"

[Plants-vs-Zombies]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
apkeep-dlurl 	= "com.ea.game.pvzfree_row"

[The-Battle-of-Polytopia]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
uptodown-dlurl 	= "https://polytopia.en.uptodown.com/android"

[Zombie-Catchers]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
apkeep-dlurl 	= "fi.twomenandadog.zombiecatchers"

# ==============================================================================
# binarymend/morphe-patches
# ==============================================================================

[CalcNote]
patches-source  = "binarymend/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "binarymend"
apkeep-dlurl 	= "com.burton999.notecal"

[Symfonium]
patches-source  	= "binarymend/morphe-patches"
cli-source      	= "MorpheApp/morphe-cli"
rv-brand        	= "binarymend"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/tolriq/symfonium-music-player-cast/"
apkeep-dlurl	 	= "app.symfonik.music.player"

# ==============================================================================
# BholeyKaBhakt/android-patches-xtra
# ==============================================================================

[Automate]
patches-source  = "BholeyKaBhakt/android-patches-xtra"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "xtra"
apkeep-dlurl 	= "com.llamalab.automate"

[Backdrops]
patches-source  = "BholeyKaBhakt/android-patches-xtra"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "xtra"
patches-version = "dev"
apkeep-dlurl 	= "com.backdrops.wallpapers"

# ==============================================================================
# jkennethcarino/adobo
# ==============================================================================

[Reddit-Adobo]
patches-source  = "jkennethcarino/adobo"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "adobo"
patches-version = "dev"
uptodown-dlurl  = "https://reddit-official-app.en.uptodown.com/android"
apkeep-dlurl  	= "com.reddit.frontpage"


# ==============================================================================
# kiraio-moe/Lain-Patches
# ==============================================================================

[AudioRelay]
patches-source  = "kiraio-moe/Lain-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "lain"
apkeep-dlurl 	= "com.azefsw.audioconnect"

[Camera]
patches-source  = "kiraio-moe/Lain-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "lain"
apkeep-dlurl  	= "com.flavionet.android.camera.lite"

[iLovePDF]
patches-source  = "kiraio-moe/Lain-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "lain"
apkeep-dlurl	= "com.ilovepdf.www"

[Hidden-Settings]
patches-source  = "kiraio-moe/Lain-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "lain"
apkmirror-dlurl = "https://www.apkmirror.com/apk/yunus-ceyhan/hidden-settings-miui-hyperos/"

[Super-Proxy]
patches-source  = "kiraio-moe/Lain-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "lain"
patches-version = "dev"
uptodown-dlurl = "https://com-scheler-superproxy.en.uptodown.com/android/download"

# ==============================================================================
# durgesh0505/chiggi_morphe_patches
# ==============================================================================

[Arrow-Puzzle]
patches-source  = "durgesh0505/chiggi_morphe_patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "durgesh0505"
apkeep-dlurl  	= "com.easybrain.arrow.puzzle.game"

# ==============================================================================
# arandomhooman/hoomans-morphe-patches
# ==============================================================================

[Poweramp]
patches-source  = "arandomhooman/hoomans-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "hoomans"
uptodown-dlurl  = "https://poweramp-music-player.en.uptodown.com/android"

[Advanced-Download-Manager]
patches-source  = "arandomhooman/hoomans-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "hoomans"
apkeep-dlurl  	= "com.dv.adm"

# ==============================================================================
# bufferk/morphe-patches
# ==============================================================================

[Brave]
patches-source  = "bufferk/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "bufferk"
uptodown-dlurl	= "https://brave-software-brave.en.uptodown.com/android"

[Medium]
patches-source  = "bufferk/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "bufferk"
apkeep-dlurl	= "com.medium.reader"

[Truecaller-bufferk]
patches-source  	= "bufferk/morphe-patches"
cli-source      	= "MorpheApp/morphe-cli"
rv-brand        	= "bufferk"
# patches-version 	= "dev"
apkeep-dlurl 		= "com.truecaller"

# ==============================================================================
# Single Target Repositories (Unique Sources)
# ==============================================================================

# Aunali321/ReVancedExperiments
[Telegram]
patches-source  = "Aunali321/ReVancedExperiments"
cli-source      = "ReVanced/revanced-cli"
rv-brand        = "Aunali321"
uptodown-dlurl  = "https://telegram-google-play-version.en.uptodown.com/android"

# wchill/patcheddit
[Lemmy-Sync]
patches-source  = "wchill/patcheddit"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "patcheddit"
# patches-version = "dev"
apkeep-dlurl 	= "io.syncapps.lemmy_sync"

# prathxmOp/prathxm-patches
[Chess-com]
patches-source  = "prathxmOp/prathxm-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "Prathxm"
apkmirror-dlurl = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/"
uptodown-dlurl 	= "https://chess-play-and-learn.en.uptodown.com/android"
