parallel-jobs = 1
dpi = "nodpi anydpi"
remove-rv-integrations-checks = false
# see https://github.com/nvbangg/Patches-APK-Builder/blob/main/CONFIG.md for more detailed explanations

# [YouTube-Morphe]
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# app-name = "youtube"
# rv-brand = "morphe"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"

# [YouTube-Music-Morphe]
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# app-name = "youtube-music"
# rv-brand = "morphe"
# arch = "arm64-v8a"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

# [YouTube-Morphe-Dev]
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# app-name = "youtube-dev"
# rv-brand = "morphe"
# patches-version = "dev"
# uptodown-dlurl = "https://youtube.en.uptodown.com/android"

# [YouTube-Music-Morphe-Dev]
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# app-name = "youtube-music-dev"
# rv-brand = "morphe"
# arch = "arm64-v8a"
# patches-version = "dev"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
# uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"

# [Google-Photos-Morphe]
# patches-source = "RookieEnough/De-ReVanced"
# cli-source = "MorpheApp/morphe-cli"
# rv-brand = "de-revanced"
# uptodown-dlurl = "https://google-photos.en.uptodown.com/android"

# [Telegram]
# patches-source = "Aunali321/ReVancedExperiments"
# cli-source = "ReVanced/revanced-cli"
# uptodown-dlurl = "https://telegram-google-play-version.en.uptodown.com/android"

# [Reddit-Morphe]
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# rv-brand = "morphe"
# uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

# [Reddit-Morphe-Dev]
# patches-source = "MorpheApp/morphe-patches"
# cli-source = "MorpheApp/morphe-cli"
# rv-brand = "morphe-dev"
# patches-version = "dev"
# uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

# [Reddit-Adobo-Dev]
# patches-source = "jkennethcarino/adobo"
# cli-source = "MorpheApp/morphe-cli"
# rv-brand = "adobo-dev"
# patches-version = "dev"
# uptodown-dlurl = "https://reddit-official-app.en.uptodown.com/android"

# [Cricbuzz-Morphe]
# cli-source = "MorpheApp/morphe-cli"
# patches-source = "RookieEnough/De-ReVanced"
# uptodown-dlurl = "https://cricbuzz-cricket-scores-and-news.en.uptodown.com/android"

# [X-Twitter]
# patches-source = "crimera/piko"
# brand = "piko"
# patches-version = "dev"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/x-corp/twitter"
# uptodown-dlurl = "https://twitter.en.uptodown.com/android"
# version = "11.81.0-release.0"

# [JioTV]
# patches-source = "rabilrbl/fluffy-patches"
# cli-source = "MorpheApp/morphe-cli"
# rv-brand = "fluffy"
# patches-version = "dev"
# # apkmirror-dlurl = "https://www.apkmirror.com/apk/jio-platforms-limited/jiotv-live-sports-movies-shows/"
# uptodown-dlurl = "https://jiotv.en.uptodown.com/android"

[Wallcraft]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://wallpaperscraft.en.uptodown.com/android"

[Truecaller]
patches-source = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "paresh"
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
# uptodown-dlurl = "https://truecaller.en.uptodown.com/android"

[Truecaller-binarymend]
patches-source = "binarymend/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "binarymend"
# patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
# uptodown-dlurl = "https://truecaller.en.uptodown.com/android"

[Fing]
patches-source = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "paresh"
# dpi = "120-640dpi"
# patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/fing-limited/fing-network-tools/"
uptodown-dlurl = "https://fing-network-tools.en.uptodown.com/android"

[Lumina]
patches-source = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "paresh"
# patches-version = "dev"
uptodown-dlurl = "https://lumina-walls.en.uptodown.com/android"

[ProtonVPN]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "paresh"
patches-version = "dev"
# uptodown-dlurl = "https://protonvpn.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/proton-technologies-ag/protonvpn-free-vpn-secure-unlimited-fdroid-version/"

[WPS-Office]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/wps-software-pte-ltd/wps-office-pdf/"
uptodown-dlurl = "https://wps-office.en.uptodown.com/android"

[Tumblr]
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
# dpi = "120-640dpi"
rv-brand = "De-Vanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tumblr-inc/tumblr/"
uptodown-dlurl = "https://tumblr.en.uptodown.com/android"

[Trakt]
patches-source = "IMXEren/mix-patches"
cli-source = "MorpheApp/morphe-cli"
# dpi = "120-640dpi"
rv-brand = "IMXEren"
# apkmirror-dlurl = "https://www.apkmirror.com/apk/trakt/trakt/"
uptodown-dlurl = "https://trakt.en.uptodown.com/android"

[Telegram]
patches-source = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/telegram-fz-llc/telegram-web-version/"

[Solid-Explorer]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
apkmirror-dlurl = "https://www.apkmirror.com/apk/neatbytes/solid-explorer-file-manager/"

[Eyecon]
patches-source = "GitLab:Paresh-Maheshwari/paresh-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "paresh"
apkmirror-dlurl = "https://www.apkmirror.com/apk/eyecon-phone-dialer-contacts/eyecon-caller-id-spam-block/"

[Lyfta]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://lyfta-gym-workout-tracker-log.en.uptodown.com/android"

[Camera]
patches-source = "kiraio-moe/Lain-Patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "lain"
uptodown-dlurl = "https://camera-fv-5-lite.en.uptodown.com/android"

[MacroFactor]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
uptodown-dlurl = "https://macrofactor-diet-sidekick-and-macro-tracker.en.uptodown.com/android"

[M-Indicator]
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
patches-version = "dev"
uptodown-dlurl = "https://m-indicator.en.uptodown.com/android"

[SoundCloud-hoo-dles]
patches-source = "hoo-dles/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "hoo-dles"
# patches-version = "dev"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[SoundCloud-RookieEnough]
patches-source = "RookieEnough/De-Vanced"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "de-vanced"
# patches-version = "dev"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[SoundCloud-kondratjev]
patches-source = "kondratjev/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "kondratjev"
# patches-version = "dev"
uptodown-dlurl = "https://soundcloud.en.uptodown.com/android"

[NZB360]
patches-source = "rushiranpise/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "rushiranpise"
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/kevin-foreman/nzb360/"

[Backdrops]
patches-source = "BholeyKaBhakt/android-patches-xtra"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "xtra"
patches-version = "dev"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers/"

[YouTube-Morphe]
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
app-name = "youtube"
rv-brand = "morphe"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
patcher-args = """
    -e 'MaterialYou' \
    -e 'Return YouTube Username' \
    -e 'Custom branding icon for YouTube' -OappIcon='mmt_turquoise' -OchangeSplashIcon='true' -OrestoreOldSplashAnimation='true' \
    -e 'Custom header for YouTube' -OcustomHeader='custom_branding_icon' \
    -e 'Theme' -OdarkThemeBackgroundColor=@android:color/black \
    -e 'Settings for YouTube' -OrvxSettingsLabel='Revanced Extended' -OinsertPosition=@string/about_key
    """

[Minesweeper]
patches-source = "cesbar/zpatches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "cesbar"
uptodown-dlurl = "https://minesweeper-the-clean-one.en.uptodown.com/android"
