# binarymend/morphe-patches
#
# Patches bundle: https://github.com/binarymend/morphe-patches
# CLI:            https://github.com/MorpheApp/morphe-cli

[CalcNote]
patches-source  = "binarymend/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "binarymend"
apkeep-dlurl 	= "com.burton999.notecal"
