# binarymend/morphe-patches
#
# Patches bundle: https://github.com/binarymend/morphe-patches
# CLI:            https://github.com/MorpheApp/morphe-cli

# every <source>-dlurl below is tried in DL_SRCS order
# (apkeep, apkcombo, apkmirror, apkpure, gplaydl, uptodown) and the next one
# is used when the current one cannot serve the required version.

[Truecaller-binarymend]
patches-source  = "binarymend/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "binarymend"
apkeep-dlurl    	= "com.truecaller"
apkcombo-dlurl  	= "https://apkcombo.com/truecaller/com.truecaller/"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/true-software-scandinavia-ab/truecaller-caller-id-block/"
apkpure-dlurl   	= "https://apkpure.net/truecaller/com.truecaller"
uptodown-dlurl  	= "https://truecaller.en.uptodown.com/android"
