# cesbar/zpatches
#
# Patches bundle: https://github.com/cesbar/zpatches
# CLI:            https://github.com/MorpheApp/morphe-cli

# every <source>-dlurl below is tried in DL_SRCS order
# (apkeep, apkcombo, apkmirror, apkpure, gplaydl, uptodown) and the next one
# is used when the current one cannot serve the required version.

[Solitaire]
patches-source  = "cesbar/zpatches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "cesbar"
# patches-version = "dev"
apkeep-dlurl    	= "ee.dustland.android.solitaire"
apkcombo-dlurl  	= "https://apkcombo.com/solitaire/ee.dustland.android.solitaire/"
apkpure-dlurl   	= "https://apkpure.net/solitaire/ee.dustland.android.solitaire"
uptodown-dlurl  	= "https://solitaire-the-clean-one.en.uptodown.com/android"

[Minesweeper]
patches-source  = "cesbar/zpatches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "cesbar"
# patches-version = "dev"
apkeep-dlurl    	= "ee.dustland.android.minesweeper"
apkcombo-dlurl  	= "https://apkcombo.com/minesweeper/ee.dustland.android.minesweeper/"
apkpure-dlurl   	= "https://apkpure.net/minesweeper/ee.dustland.android.minesweeper"
uptodown-dlurl  	= "https://minesweeper-the-clean-one.en.uptodown.com/android"
