# dh6k/morphe-patches
#
# Patches bundle: https://github.com/dh6k/morphe-patches
# CLI:            https://github.com/MorpheApp/morphe-cli

# every <source>-dlurl below is tried in DL_SRCS order
# (apkeep, apkcombo, apkmirror, apkpure, gplaydl, uptodown) and the next one
# is used when the current one cannot serve the required version.

[Brave-dh6k]
patches-source  = "dh6k/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "dh6k"
apkeep-dlurl    	= "com.brave.browser"
apkcombo-dlurl  	= "https://apkcombo.com/brave-dh6k/com.brave.browser/"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/brave-software/brave-browser/"
uptodown-dlurl  	= "https://brave-software-brave.en.uptodown.com/android"

[Brave-Beta-dh6k]
patches-source  = "dh6k/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "dh6k-beta"
apkeep-dlurl    	= "com.brave.browser_beta"
apkcombo-dlurl  	= "https://apkcombo.com/brave-beta-dh6k/com.brave.browser_beta/"
apkmirror-dlurl 	= "http://apkmirror.com/apk/brave-software/brave-browser-beta/"
uptodown-dlurl  	= "https://brave-browser-beta.en.uptodown.com/android"

[Brave-Nightly-dh6k]
patches-source  = "dh6k/morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "dh6k-nightly"
apkeep-dlurl    	= "com.brave.browser_nightly"
apkcombo-dlurl  	= "https://apkcombo.com/brave-nightly-dh6k/com.brave.browser_nightly/"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/brave-software/brave-browser-nightly/"
uptodown-dlurl  	= "https://brave-browser-nightly.en.uptodown.com/android"
