# Entree3k/Morning-Entree-Patches
#
# Patches bundle: https://github.com/Entree3k/Morning-Entree-Patches
# CLI:            https://github.com/MorpheApp/morphe-cli

[Arm-Workout]
patches-source  = "Entree3k/Morning-Entree-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "Entree3k"
uptodown-dlurl 	= "https://arm-workout.en.uptodown.com/android"

[Does-Not-Commute-Entree3k]
patches-source  = "Entree3k/Morning-Entree-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "Entree3k"
apkeep-dlurl  	= "com.mediocre.commute"

[Home-Workout]
patches-source  = "Entree3k/Morning-Entree-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "Entree3k"
uptodown-dlurl 	= "https://leap-fitness-group-home-workout.en.uptodown.com/android"

[Lose-Weight-App-for-Men]
patches-source  = "Entree3k/Morning-Entree-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "Entree3k"
uptodown-dlurl 	= "https://lose-weight-app-for-men.en.uptodown.com/android"

[MacroDroid-Entree3k]
patches-source  = "Entree3k/Morning-Entree-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "Entree3k"
apkeep-dlurl 	= "com.arlosoft.macrodroid"

[PinOut]
patches-source  = "Entree3k/Morning-Entree-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "Entree3k"
apkeep-dlurl 	= "com.mediocre.pinout"

[Six-Pack-in-30-Days]
patches-source  = "Entree3k/Morning-Entree-Patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "Entree3k"
uptodown-dlurl	= "https://six-pack-in-30-days.en.uptodown.com/android"
