# MiguelNinja19/miguel-morphe-patches
#
# Patches bundle: https://github.com/MiguelNinja19/miguel-morphe-patches
# CLI:            https://github.com/MorpheApp/morphe-cli

[Anger-of-Stick-5]
patches-source  	= "MiguelNinja19/miguel-morphe-patches"
cli-source      	= "MorpheApp/morphe-cli"
rv-brand        	= "MiguelNinja19"
version 			= "latest"
apkeep-dlurl 		= "jpark.AOS5"

[Climb]
patches-source  	= "MiguelNinja19/miguel-morphe-patches"
cli-source      	= "MorpheApp/morphe-cli"
rv-brand        	= "MiguelNinja19"
version 			= "latest"
apkcombo-dlurl		= "https://apkcombo.com/climb-amiyp/com.IvanAF.ClimbAMIYPfree/"
uptodown-dlurl	 	= "https://climb-free.en.uptodown.com/android"

[CubeX-Solver]
patches-source  	= "MiguelNinja19/miguel-morphe-patches"
cli-source      	= "MorpheApp/morphe-cli"
rv-brand        	= "MiguelNinja19"
version 			= "latest"
apkeep-dlurl		= "diozz.cubex"

[Hunter-Assassin]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
apkeep-dlurl 	= "com.rubygames.assassin"

[Oddmar]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
apkeep-dlurl 	= "com.mobge.Oddmar"

[Plants-vs-Zombies]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
apkeep-dlurl 	= "com.ea.game.pvzfree_row"

[The-Battle-of-Polytopia]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
uptodown-dlurl 	= "https://polytopia.en.uptodown.com/android"

[Zombie-Catchers]
patches-source  = "MiguelNinja19/miguel-morphe-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "MiguelNinja19"
version 		= "latest"
apkeep-dlurl 	= "fi.twomenandadog.zombiecatchers"
