# MorpheApp/morphe-patches
#
# Patches bundle: https://github.com/MorpheApp/morphe-patches
# CLI:            https://github.com/MorpheApp/morphe-cli

[YouTube-Morphe]
patches-source 		= "MorpheApp/morphe-patches"
cli-source 			= "MorpheApp/morphe-cli"
rv-brand 			= "morphe"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/google-inc/youtube/"
apkeep-dlurl 		= "com.google.android.youtube"

[YouTube-Morphe-Dev]
patches-source 		= "MorpheApp/morphe-patches"
cli-source 			= "MorpheApp/morphe-cli"
rv-brand 			= "morphe-dev"
patches-version 	= "dev"
version				= "experiment"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/google-inc/youtube/"
apkeep-dlurl 		= "com.google.android.youtube"

[YouTube-Music-Morphe]
patches-source 	= "MorpheApp/morphe-patches"
cli-source 		= "MorpheApp/morphe-cli"
rv-brand		= "morphe"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkeep-dlurl 	= "com.google.android.apps.youtube.music"

[YouTube-Music-Morphe-Dev]
patches-source 		= "MorpheApp/morphe-patches"
cli-source 			= "MorpheApp/morphe-cli"
rv-brand 			= "morphe-dev"
patches-version 	= "dev"
version				= "experiment"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkeep-dlurl 		= "com.google.android.apps.youtube.music"

[Reddit-Morphe]
patches-source 	= "MorpheApp/morphe-patches"
cli-source 		= "MorpheApp/morphe-cli"
rv-brand		= "morphe"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/redditinc/reddit/"
# uptodown-dlurl  = "https://reddit-official-app.en.uptodown.com/android"
apkeep-dlurl  	= "com.reddit.frontpage"

[Reddit-Morphe-Dev]
patches-source 	= "MorpheApp/morphe-patches"
cli-source 		= "MorpheApp/morphe-cli"
rv-brand		= "morphe-dev"
patches-version = "dev"
version			= "experiment"
apkmirror-dlurl 	= "https://www.apkmirror.com/apk/redditinc/reddit/"
# uptodown-dlurl  = "https://reddit-official-app.en.uptodown.com/android"
apkeep-dlurl  	= "com.reddit.frontpage"
