# prathxmOp/prathxm-patches
#
# Patches bundle: https://github.com/prathxmOp/prathxm-patches
# CLI:            https://github.com/MorpheApp/morphe-cli

[Chess-com]
patches-source  = "prathxmOp/prathxm-patches"
cli-source      = "MorpheApp/morphe-cli"
rv-brand        = "Prathxm"
apkmirror-dlurl = "https://www.apkmirror.com/apk/chess-com/chess-play-learn/"
uptodown-dlurl 	= "https://chess-play-and-learn.en.uptodown.com/android"
